Compras/Compras/Controllers/Articulos_DepartamentosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Compras;

namespace Compras.Controllers
{
    public class Articulos_DepartamentosController : Controller
    {
        private ComprasEntities db = new ComprasEntities();

        // GET: Articulos_Departamentos
        public ActionResult Index()
        {
            var articulos_Departamentos = db.Articulos_Departamentos.Include(a => a.Articulo).Include(a => a.Departamento);
            return View(articulos_Departamentos.ToList());
        }

        // GET: Articulos_Departamentos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articulos_Departamentos articulos_Departamentos = db.Articulos_Departamentos.Find(id);
            if (articulos_Departamentos == null)
            {
                return HttpNotFound();
            }
            return View(articulos_Departamentos);
        }

        // GET: Articulos_Departamentos/Create
        public ActionResult Create()
        {
            ViewBag.ID_arti = new SelectList(db.Articulos, "ID_arti", "Descripcion");
            ViewBag.ID_dp = new SelectList(db.Departamentos, "ID_dp", "Nombre");
            return View();
        }

        // POST: Articulos_Departamentos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_ardep,ID_arti,ID_dp")] Articulos_Departamentos articulos_Departamentos)
        {
            if (ModelState.IsValid)
            {
                db.Articulos_Departamentos.Add(articulos_Departamentos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_arti = new SelectList(db.Articulos, "ID_arti", "Descripcion", articulos_Departamentos.ID_arti);
            ViewBag.ID_dp = new SelectList(db.Departamentos, "ID_dp", "Nombre", articulos_Departamentos.ID_dp);
            return View(articulos_Departamentos);
        }

        // GET: Articulos_Departamentos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articulos_Departamentos articulos_Departamentos = db.Articulos_Departamentos.Find(id);
            if (articulos_Departamentos == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_arti = new SelectList(db.Articulos, "ID_arti", "Descripcion", articulos_Departamentos.ID_arti);
            ViewBag.ID_dp = new SelectList(db.Departamentos, "ID_dp", "Nombre", articulos_Departamentos.ID_dp);
            return View(articulos_Departamentos);
        }

        // POST: Articulos_Departamentos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_ardep,ID_arti,ID_dp")] Articulos_Departamentos articulos_Departamentos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articulos_Departamentos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_arti = new SelectList(db.Articulos, "ID_arti", "Descripcion", articulos_Departamentos.ID_arti);
            ViewBag.ID_dp = new SelectList(db.Departamentos, "ID_dp", "Nombre", articulos_Departamentos.ID_dp);
            return View(articulos_Departamentos);
        }

        // GET: Articulos_Departamentos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articulos_Departamentos articulos_Departamentos = db.Articulos_Departamentos.Find(id);
            if (articulos_Departamentos == null)
            {
                return HttpNotFound();
            }
            return View(articulos_Departamentos);
        }

        // POST: Articulos_Departamentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Articulos_Departamentos articulos_Departamentos = db.Articulos_Departamentos.Find(id);
            db.Articulos_Departamentos.Remove(articulos_Departamentos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Compras/Compras/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <div class="container body-content content">
        @RenderBody()
        <hr />
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>




        <script type='text/javascript'>
            var appInsights = window.appInsights || function (config) {
                function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }
                var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;) r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o), s }), t
            }({
                instrumentationKey: '1d738889-db39-40da-b9b3-8cdcb6ea0c92'
            });

            window.appInsights = appInsights;
            appInsights.trackPageView();
        </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Articulos", "Index", "Articulos")</li>
                    <li>@Html.ActionLink("Articulos por Departamentos", "Index", "Articulos_Departamentos")</li>
                    <li>@Html.ActionLink("Direcciones", "Index", "Direcciones")</li>
                    <li>@Html.ActionLink("Proveedores", "Index", "Proveedores")</li>
                    <li>@Html.ActionLink("Identificaciones", "Index", "Identificaciones")</li>
                    <li>@Html.ActionLink("Medidas", "Index", "Medidas")</li>
                    <li>@Html.ActionLink("Departamentos", "Index", "Departamentos")</li>
                    <li>@Html.ActionLink("Ordenes", "Index", "Ordenes")</li>
                </ul>
            </div>
        </div>
    </div>
    
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-2.2.3.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/app.min.js"></script>
    
</body>
</html>